### ISSUE TITLE
Client build with session authscheme fails with "token required"

### ISSUE THREAD

**Issue by shivchelwa** [influxdata/influxdb-client-java#178]
__Steps to reproduce:__

1. Build InfluxDBClientOptions using InfluxDBClientOptions.builder().connectionString(connStr).org(org).bucket(bucket).authenticate(user, pwd.toCharArray()).build()
2. Create InfluxDBClient using InfluxDBClientFactory.create(clientOptions)
3. Write a point using influxDBClient.getWriteApi().writePoints(points)

__Expected behavior:__
Session authentication scheme should be used and point is written to InfluxDB

__Actual behavior:__
Get a exception `"com.influxdb.exceptions.UnauthorizedException: unauthorized access"`. On InfluxDB server an error is seen `ts=2020-11-20T03:14:43.571574Z lvl=info msg=Unauthorized log_id=0Q_QdXh0000 error="token required"`

__Specifications:__
 - Client Version: 1.13.0
 - InfluxDB Version: 2.0.1
 - JDK Version: jdk-11.0.4
 - Platform: MacOS

**Comment by shivchelwa** [comment]
The connection string looks like `http://localhost:8086?writeTimeout=1000&connectTimeout=1000&logLevel=BODY`

This work fine if InfluxDBClientOptions is build using url instead of connection string e.g.  InfluxDBClientOptions.builder().**url(influxdbUrl)**.org(org).bucket(bucket).authenticate(user, pwd.toCharArray()).build()

**Comment by bednar** [comment]
Hi @shivchelwa,

thanks for report the issue.

The problem is in constructing url in the `AuthenticateInterceptor`: https://github.com/influxdata/influxdb-client-java/blob/7787a6fd5f6c13e0aad1d349e2fbdf84487a6bf6/client/src/main/java/com/influxdb/client/internal/AuthenticateInterceptor.java#L120

We should use `okhttp3.HttpUrl` instead concatenation via `+`, because `http://localhost:8086/` + `/api/v2/signin` is not valid URL.

Regards
