### ISSUE TITLE
The Question Of WriteAPI:204 No Content

### ISSUE THREAD

**Issue by 9odes** [influxdata/influxdb-client-java#208]
Hello,
    This information is returned when I write data using the write API：
    `2021-03-23 09:34:22.330  INFO 17276 --- [readScheduler-2] okhttp3.OkHttpClient:--> POST http://127.0.0.1:8086/api/v2/write?org=his&bucket=hiiot&precision=ns (147-byte body)
2021-03-23 09:34:22.422  INFO 17276 --- [readScheduler-2] okhttp3.OkHttpClient:<-- 204 No Content http://127.0.0.1:8086/api/v2/write?org=his&bucket=hiiot&precision=ns (92ms,0-byte body)`
Then I query the data：
`from(bucket: "hiiot")
    |> range(start: 0) 
    |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")`
But I can't find this data util 2 min later.Can you tell me where I'm wrong or which parameter  I need to configure?

write code:
`WriteOptions writeOptions = WriteOptions.builder()
                .batchSize(5000)
              .flushInterval(1000)
                .bufferLimit(10000)
                .jitterInterval(1000)
                .retryInterval(5000)
                .build();
        try (WriteApi writeApi = influxDBClient.getWriteApi(writeOptions)) {
            writeApi.writePoints(bucket, org, points);
        }`
java:1.8
influxdb-client-java:1.15.0
influxdb:2.0.3

**Comment by bednar** [comment]
Hi @9odes,

thanks for using our client.

> Hello,
> This information is returned when I write data using the write API：
> `2021-03-23 09:34:22.330 INFO 17276 --- [readScheduler-2] okhttp3.OkHttpClient:--> POST http://127.0.0.1:8086/api/v2/write?org=his&bucket=hiiot&precision=ns (147-byte body) 2021-03-23 09:34:22.422 INFO 17276 --- [readScheduler-2] okhttp3.OkHttpClient:<-- 204 No Content http://127.0.0.1:8086/api/v2/write?org=his&bucket=hiiot&precision=ns (92ms,0-byte body)`
> Then I query the data：
> `from(bucket: "hiiot") |> range(start: 0) |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")`
> But I can't find this data util 2 min later.Can you tell me where I'm wrong or which parameter I need to configure?

The problem is that the `log` contains information about written data, but you are not able to query this data. Is it correct?

> write code:
> `WriteOptions writeOptions = WriteOptions.builder() .batchSize(5000) .flushInterval(1000) .bufferLimit(10000) .jitterInterval(1000) .retryInterval(5000) .build(); try (WriteApi writeApi = influxDBClient.getWriteApi(writeOptions)) { writeApi.writePoints(bucket, org, points); }`

The `WriteApi` is suppose to be a long live singleton, but you are immediately closing the `WriteApi` by `try-resource`. How much points your collection contains?

I think the better solution for you will be a [WriteApiBlocking](https://github.com/influxdata/influxdb-client-java/blob/master/client/src/main/java/com/influxdb/client/WriteApiBlocking.java). Something like will fits your requirements:

```java
WriteApiBlocking writeApi = influxDBClient.getWriteApiBlocking();
writeApi.writePoints(bucket, org, points); 
```

Regards

**Comment by 9odes** [comment]
Hi, @bednar I used this method, but the problem was not solved. I can query this data, but I need to wait for two minutes.
I want to query it as soon as I write the data

**Comment by bednar** [comment]
@9odes It could be caused by timestamp of your data. The [range()](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/range/) function has `stop` parameter defined as `stop: now()`.

How your data looks like? 
Could you test the query with `stop` parameter in future? Something like:

```
from(bucket: "hiiot")
  |> range(start: 0, stop: 2h)
```

**Comment by 9odes** [comment]
@bednar OK，You are right.It was caused by timestamp. The problem has been solved. Thank you!
