### ISSUE TITLE
Add support for gzip compression of query response

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb-client-java#50]
The clients should support compress queries after enable gzip: `influxDBClient.enableGzip();`

https://github.com/influxdata/influxdb/pull/14495

**Comment by antoinedvd** [comment]
👋 Hi folks, I not quite sure that really works from a query executed by kotlin-client.  
Indeed, the facts that we set `application/json` by default for all `query()` calls that blocks the `BridgeInterceptor` to do his job to add the `Accept-Encoding: gzip` header.   
IMO the `Accept-Encoding: application/json` is not used by the InfluxDB server because it always sent you back `application/csv` data (for and InfluxDB 2.0 server with Flux request).  
 
👉 So I have a [commit ready to PR](https://github.com/antoinedvd/influxdb-client-java/commit/667afd06f2e32a017f4cfc6728b5ea4b5aa075fb) if you want, to fix this issue.   

💬 Let me know what do you think of it, and if you want I am create it.

**Comment by bednar** [comment]
Hi @antoinedvd,

thanks for your comment. The default value for `Accept-Encoding` should be `identity`. The `GZIP` compression is managed by [GzipInterceptor.java](https://github.com/influxdata/influxdb-client-java/blob/59fbec92d7225e0148a1e601b50ea8b111147e72/client/src/main/java/com/influxdb/client/internal/GzipInterceptor.java#L41).

You could enable `GZIP` compression by:

```kotlin
var influxDBClient = influxDBClient.enableGzip()
```
https://github.com/influxdata/influxdb-client-java/blob/master/client-kotlin/src/main/kotlin/com/influxdb/client/kotlin/InfluxDBClientKotlin.kt#L71

Could you prepare a PR with `Accept-Encoding: identity`?

Regards

**Comment by antoinedvd** [comment]
Hi @bednar, 

Thank you for your answerd. 

Of course I tried to use the `var influxDBClient = influxDBClient.enableGzip()` but that didn't works well.
If you look here : https://github.com/influxdata/influxdb-client-java/blob/c6aaa5717dc053b84eea7be1c8937dfa9c36fc5e/client/src/main/java/com/influxdb/client/internal/GzipInterceptor.java#L79 Its clearly wrote that gzip header is added by `Bridge interceptor`. 
So if I add `Accept-Encoding: identity` the same issue will be produced. 😃

**Comment by bednar** [comment]
> So if I add Accept-Encoding: identity the same issue will be produced. Don't you think ?
You are right, sorry for wrong direction ... feel free to create PR

**Comment by antoinedvd** [comment]
@bednar no pb 😉 
I will create the PR. 
Thank you for your reactivity ! 👍🏻
